# @package _group_

fairseq:
  task:
    _name: unpaired_audio_text
    labels: phn
    #data: ???
    data: /u/enrique.leon.lozano/setups/ubuntu_22_setups/fairseq_2025_03_11/work/i6_experiments/users/enrique/jobs/wav2vec_u_audio_preprocessing/Wav2VecUFeaturizeAudioJob.TyJVh2DlIY8F/output/audio_features/precompute_pca512_cls128_mean
    sort_by_length: false
    shuffle: false
    text_data: ''

  common_eval:
    path: ???
    quiet: true

  dataset:
    gen_subset: valid
    batch_size: 1

w2l_decoder: VITERBI
post_process: silencez
