[tool.black]
line-length = 120
target-version = ["py38"]
# exclude = 'users'

[tool.ruff]
line-length = 120

[tool.pyright]
reportMissingModuleSource = false
reportUnusedImport = true
pythonVersion = "3.8"
typeCheckingMode = "basic"
extraPaths = [
  "../",
  "/work/asr4/berger/rasr_dev/label_scorer/rasr/arch/linux-x86_64-standard/",
]
